/** Label every note carries: it's generated from a conversation and must be checked. */
export const DRAFT_LABEL = "DRAFT: generated by AI, for clinician review";

export type SpeakerRole = "doctor" | "patient" | "multiple";

export interface TranscriptSegment {
  id: string;
  channel: number;
  role: SpeakerRole;
  text: string;
  /** Interim segments are replaced by a final one with the same id. */
  final: boolean;
  /** As reported by Corti (the unit is to be confirmed against the live API). */
  start: number;
  end: number;
}

export interface Fact {
  id: string;
  text: string;
  group: string;
  source: string;
}

export interface NoteSection {
  key: string;
  heading: string;
  text: string;
}

export interface DraftNote {
  status: "draft";
  label: typeof DRAFT_LABEL;
  interactionId: string;
  documentId: string;
  templateKey: string;
  language: string;
  /** What the note was generated from: facts when there are any, else the transcript. */
  basedOn: "facts" | "transcript";
  sections: NoteSection[];
  generatedAt: string;
}
